export const usStates = [
  { id: 1, name: 'Alabama', short: 'AL' },
  { id: 2, name: 'Alaska', short: 'AK' },
  { id: 3, name: 'Arizona', short: 'AZ' },
  { id: 4, name: 'Arkansas', short: 'AR' },
  { id: 5, name: 'California', short: 'CA' },
  { id: 6, name: 'Colorado', short: 'CO' },
  { id: 7, name: 'Connecticut', short: 'CT' },
  { id: 8, name: 'Delaware', short: 'DE' },
  { id: 9, name: 'Florida', short: 'FL' },
  { id: 10, name: 'Georgia', short: 'GA' },
  { id: 11, name: 'Hawaii', short: 'HI' },
  { id: 12, name: 'Idaho', short: 'ID' },
  { id: 13, name: 'Illinois', short: 'IL' },
  { id: 14, name: 'Indiana', short: 'IN' },
  { id: 15, name: 'Iowa', short: 'IA' },
  { id: 16, name: 'Kansas', short: 'KS' },
  { id: 17, name: 'Kentucky', short: 'KY' },
  { id: 18, name: 'Louisiana', short: 'LA' },
  { id: 19, name: 'Maine', short: 'ME' },
  { id: 20, name: 'Maryland', short: 'MD' },
  { id: 21, name: 'Massachusetts', short: 'MA' },
  { id: 22, name: 'Michigan', short: 'MI' },
  { id: 23, name: 'Minnesota', short: 'MN' },
  { id: 24, name: 'Mississippi', short: 'MS' },
  { id: 25, name: 'Missouri', short: 'MO' },
  { id: 26, name: 'Montana', short: 'MT' },
  { id: 27, name: 'Nebraska', short: 'NE' },
  { id: 28, name: 'Nevada', short: 'NV' },
  { id: 29, name: 'New Hampshire', short: 'NH' },
  { id: 30, name: 'New Jersey', short: 'NJ' },
  { id: 31, name: 'New Mexico', short: 'NM' },
  { id: 32, name: 'New York', short: 'NY' },
  { id: 33, name: 'North Carolina', short: 'NC' },
  { id: 34, name: 'North Dakota', short: 'ND' },
  { id: 35, name: 'Ohio', short: 'OH' },
  { id: 36, name: 'Oklahoma', short: 'OK' },
  { id: 37, name: 'Oregon', short: 'OR' },
  { id: 38, name: 'Pennsylvania', short: 'PA' },
  { id: 39, name: 'Rhode Island', short: 'RI' },
  { id: 40, name: 'South Carolina', short: 'SC' },
  { id: 41, name: 'South Dakota', short: 'SD' },
  { id: 42, name: 'Tennessee', short: 'TN' },
  { id: 43, name: 'Texas', short: 'TX' },
  { id: 44, name: 'Utah', short: 'UT' },
  { id: 45, name: 'Vermont', short: 'VT' },
  { id: 46, name: 'Virginia', short: 'VA' },
  { id: 47, name: 'Washington', short: 'WA' },
  { id: 48, name: 'West Virginia', short: 'WV' },
  { id: 49, name: 'Wisconsin', short: 'WI' },
  { id: 50, name: 'Wyoming', short: 'WY' },
];
